version: "3.3"
services:
  nodejs:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: openai-connect-node
    command: node index.js
    container_name: openai-connect-node
    restart: always
    env_file: .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
